### ISSUE TITLE
Scripts do not execute after installation

### ISSUE THREAD

**Issue by xxl007** [henzler/neuralmaterial#1]
None of the scripts execute after installation as per the instructions. This issue is apparently due to mismatches in dependencies.

Upon first execution, I got : 
_'ModuleNotFoundError: No module named 'tensorboard''_

After installing tensorboard via pip, I got: 
_'ModuleNotFoundError: No module named 'kornia''_

After installing kornia via pip, I got: 
_op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file_

Installed on Ubuntu 18.04 and 20.04 on a gcp cloud VM with a T4 GPU without success.

Could you please review that the installation instructions are accurate?

Thanks

**Comment by LcenArthas** [comment]
I have the same problem

**Comment by henzler** [comment]
I just uploaded a complete environment.yml. That should help!

**Comment by xxl007** [comment]
Thanks for uploading @henzler  it helps.
