### ISSUE TITLE
error loading the pretrained model

### ISSUE THREAD

**Issue by sepideh-srj** [henzler/neuralmaterial#2]
Hi,

I get this error when I try to test the model:
"_pickle.UnpicklingError: invalid load key, 'v'."
I think it might have something to do with the model being uploaded to github, could you please upload it to google drive? @henzler 

Thanks

**Comment by xxl007** [comment]
Downloading the [weights from github](https://github.com/henzler/neuralmaterial/raw/master/trainings/Neuralmaterial/checkpoint/latest.ckpt) helps here. Cloning doesn't copy the weights because of the size of the binaries.

**Comment by sepideh-srj** [comment]
thank you, it's working now.
